name: phone_number
description: Flutter plugin for parsing, formatting and validating international phone numbers.
version: 0.6.0+2
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
